FROM zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest

# Establecer variables de entorno
ENV DB_SERVER_HOST=mysql-server
ENV MYSQL_USER=zabbix
ENV MYSQL_PASSWORD=zabbix
ENV ZBX_SERVER_HOST=zabbix-server
ENV PHP_TZ=Europe/Riga

# Exponer el puerto 80
EXPOSE 80

# Comando para iniciar el contenedor
CMD ["nginx", "-g", "daemon off;"]
