apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
  template:
    metadata:
      labels:
        app: zabbix
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-7.2-latest
          ports:
            - containerPort: 80
          env:
            - name: DB_SERVER_HOST
              value: "mysql-server"
            - name: MYSQL_USER
              value: "zabbix"
            - name: MYSQL_PASSWORD
              value: "zabbix"
            - name: ZBX_SERVER_HOST
              value: "zabbix-server"
            - name: PHP_TZ
              value: "Europe/Madrid"
