name: Zabbix-Nginx-MySQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Usamos la versión v3 de checkout

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Usamos la versión más reciente de Buildx

    - name: Cache Docker layers
      uses: actions/cache@v3  # Actualizado a v3 para evitar la deprecación
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t zabbix-web-nginx-mysql .

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag zabbix-web-nginx-mysql:latest ${{ secrets.DOCKER_USERNAME }}/zabbix-web-nginx-mysql:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/zabbix-web-nginx-mysql:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3  # Usamos la versión v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/zabbix-deployment.yml
        kubectl apply -f kubernetes/zabbix-service.yml

